### ISSUE TITLE
1.1.0 Release Tag

### ISSUE THREAD

**Issue by yewscion** [VitoVan/xml-emitter#10]
As there was a version bump to 1.1.0 with commit 1a93a5ab084a10f3b527db3043bd0ba5868404bf, could there be a release tag created to explicitly call that commit the 1.1.0 version of this project? It would make it easier to package for others.

**Comment by VitoVan** [comment]
https://github.com/VitoVan/xml-emitter/tree/1.1.0

https://github.com/VitoVan/xml-emitter/releases/tag/1.1.0
